version: '3.8'

services:
  # Base de datos MySQL
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_NAME:-tideLit_db}
      MYSQL_USER: ${DB_USER:-laravel}
      MYSQL_PASSWORD: ${DB_PASSWORD:-LaravelROOT2024!}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - webproxy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Aplicación Symfony
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - APP_ENV=prod
      - APP_SECRET=${APP_SECRET:-your-secret-key-change-in-production}
      - DATABASE_URL=mysql://${DB_USER:-laravel}:${DB_PASSWORD:-LaravelROOT2024!}@database:3306/${DB_NAME:-tideLit_db}?serverVersion=8.0.32&charset=utf8mb4
    volumes:
      - app_cache:/var/www/html/var/cache
      - app_logs:/var/www/html/var/log
    networks:
      - webproxy
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/books"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mysql_data:
    driver: local
  app_cache:
    driver: local
  app_logs:
    driver: local

networks:
  webproxy:
    external: true
